# Setup
title:               Dev Blog
tagline:             'ye-geeee'
description:         '<a href="https://github.com/ye-geeee" target="_blank">Ye-Geeee</a><br/>Wi-Fi Developer at @Samsung Electronics.'
url:                 https://ye-geeee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yeji Kang
  url:               https://github.com/ye-geeee
  email:             yeaji9683@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
